class Categorias {
  static const List<String> lista = [
    'Clases particulares',
    'Idiomas',
    'Refuerzo escolar',
    'Programación',
    'Música',
    'Preparación de exámenes',
    'Clases online',
    'Desarrollo web',
    'Desarrollo de apps',
    'Soporte técnico',
    'Informática básica',
    'Ciberseguridad',
    'Edición de vídeo',
    'Edición de imagen',
    'Diseño gráfico',
    'Modelado 3D',
    'Reparaciones',
    'Fontanería',
    'Electricidad',
    'Carpintería',
    'Pintura',
    'Montaje de muebles',
    'Reformas',
    'Jardinería',
    'Limpieza del hogar',
    'Salud',
    'Entrenamiento personal',
    'Nutrición',
    'Masajes',
    'Yoga',
    'Meditación',
    'Fisioterapia',
    'Fotografía',
    'Ilustración',
    'Diseño de logos',
    'Redacción de contenidos',
    'Copywriting',
    'Escritura creativa',
    'Creación de guiones',
    'Marketing digital',
    'Redes sociales',
    'Gestión de proyectos',
    'Asesoría laboral',
    'Asesoría fiscal',
    'Contabilidad',
    'Emprendimiento',
    'Cuidado de personas mayores',
    'Cuidado de niños',
    'Cuidado de mascotas',
    'Paseo de perros',
    'Clases deportivas',
    'Deporte',
    'Traducción',
    'Organización de eventos',
    'Community manager',
    'Atención al cliente',
    'Otros servicios',
  ];
}